server:
  port: 8762

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  application:
    name: kgt-registry

eureka:
  dashboard:
    path: /ui
  instance:
    prefer-ip-address: true
    non-secure-port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
